import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import JsonData from "../Industries/Catagoriesdata/Catagoriesdata.json"
import Header from '../Industries/Header/Header'
import styled from "styled-components"
import Image from 'next/image'
import Imagefromservices from"../../Assets/Images/foot.webp"

function Servicesdetail() {
    const Main=styled.main``
    console.log("Json",JsonData.Hello)


  return (
    <>
      <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      <Main>
        
      
        <div className='col-md-12 display_overflow_hidden  '>
            <Header />
            
            <div className="row ">
                <div className='col-md-6'>
                    <Image className='img-fluid' src={Imagefromservices} width={1000} height={1000} alt="image crashed" />
                </div>
                <div className='col-md-6 m-auto px-5'>
                    <h3>Manicure Pedicure</h3>
                    <p><span className='span_1'>From</span>&nbsp;&nbsp;&nbsp; <span className='span_2'> Rs.35 </span></p><br/>
                    {/* <p className='text_des_details'>{JsonData.Details.description}</p> */}
                    <Link className='simple_decoration_link' href={`/Services-sub-services/1`}> <button className='btn btn-danger btn-sm btn_style_red'> Service not Available </button> </Link>
                </div>
            </div>
        </div>
   
       </Main>
    </>
  )
}

export default Servicesdetail