import Head from 'next/head'
import { Inter } from '@next/font/google'
import React, {useEffect} from 'react'
import Header from "../Industries/Header/Header"
import styled from "styled-components"
import Link from 'next/link'
import JsonData from "../Industries/Catagoriesdata/Catagoriesdata.json"

 
 
const inter = Inter({ subsets: ['latin'] })





export default function Details() {


  console.log(JsonData.Details)
  const Main=styled.main``
  const margin_cards = {
    marginTop:"30px",
    cursor:"pointer"
 }


  
  return (
    <>
      <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      <Main>
        
      
        <div className='col-md-12 display_overflow_hidden  '>
            <Header />
            
            <div className="row ">
                <div className='col-md-6'>
                    <img className='img-fluid' src='../images/man.webp' />
                </div>
                <div className='col-md-6 m-auto px-5'>
                    <h3>{JsonData.Details.title}</h3>
                    <p><span className='span_1'>From</span>&nbsp;&nbsp;&nbsp; <span className='span_2'> Rs.{JsonData.Details.price} </span></p>
                    <p className='text_des_details'>{JsonData.Details.description}</p>
                    <Link className='simple_decoration_link' href={`/Industries-listing/1`}> <button className='btn btn-danger btn-sm btn_style_red'> Book Now </button> </Link>
                </div>
            </div>
        </div>
   
       </Main>
    </>
  )
}