import Head from 'next/head'
import Image from 'next/image'
 import Container from '@/Tags/Container/Container'
import styled from "styled-components"
import View from '@/Tags/View/View'
import Button from '@/Tags/Button/Button'
 
 
 
export default function Home() {
  const Main=styled.main``
  return (
    <>
      <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <Main>
        <Container>
          <View>Home page</View> 
          </Container>
       </Main>
    </>
  )
}