import Head from 'next/head'
import React from 'react'
import Header from '../Industries/Header/Header'
import JsonData from "../Industries/Catagoriesdata/Catagoriesdata.json"
import Link from 'next/link'
import Image from 'next/image'

function services() {
  return (
    <>
     <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      <Header />
     
        <div className='col-md-12 text-center pt-4'>
          <h5><b>Nails</b></h5>
        </div>
        <div className='col-md-12 px-3 pt-3'>
       <div className='row'>

        {JsonData.Nails.map((items, index)=>{
          return(
            <div key={index} className='col-md-3 mt-md-0 mt-4'>
            <div className='col-md-12 shadow_box'>
              <Link className='simple_decoration_link' href={`/Services-detail/${items.id}`}>
              <Image src={items.image} className='img-fluid img_border' width={1000} height={1000} alt="image crashed" />
              <div className='col-md-12 bg_card text-center'>
              {items.title}
              </div>
              </Link>
            </div>
          </div>
          )
        })}
              

        
       </div>
      </div>
      </>
  )
}

export default services