import { Main } from 'next/document'
import Head from 'next/head'
import React,{useState} from 'react'
import Header from '../Industries/Header/Header'
import styled from "styled-components"
import PhoneInput from 'react-phone-input-2'
import 'react-phone-input-2/lib/style.css'
import Link from 'next/link'

function industriesbooking() {
    const Main=styled.main``
    const [value, setValue] = useState()
  return (
    <div>
         <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      <Main>
        <Header />
          <div className='col-md-12 text-center padding_top_equal_booking_page'>
            <img className='img-fluid' src='../images/expertlog.png' />
            <div className='col-md-12 px-5 pt-4'>
                <div className='row'>
                    <div className='col-md-4'></div>
                    <div className='col-md-4 '>
                        <div className='col-md-12 text-start'>
                        <p className='mb-2 text_mobile_booking'>Enter your mobile number</p>
                        <PhoneInput
                        country={'us'}
                        value={value}
                        onChange={()=>setValue}
                        inputProps={{
                            required: true,
                            autoFocus: true
                          }}
                        />
                        <p className='mb-1 mt-1 text_mobile_booking'>By proceeding,you consent to get calls, WhatsApp or SMS messages, including by automated means, from Expert and Its affiliates to the number provided.</p>
                        <Link href="/industries-booking/industries-otp" > <button className='btn btn-danger px-4 pb-2 mt-2 background_booking_button'>
                            Next
                        </button></Link>
                        </div>
                    </div>
                    <div className='col-md-4'></div>
                </div>
            </div>
          </div>
        </Main>
        </div>
  )
}

export default industriesbooking