import Head from 'next/head'
import React,{useEffect, useState} from 'react'
import Header from '../Industries/Header/Header'
import styled from "styled-components"
import Link from 'next/link'
import { AiOutlineEye, AiOutlineEyeInvisible } from "react-icons/ai";
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';

function Industriespassword() {
  const [showPassword, setShowPassword] = useState(true);
  const [value, setValue] = useState('')
  const [value1, setValue1] = useState('')
  const [passwordShown, setPasswordShown] = useState(false);
  const [passwordShown1, setPasswordShown1] = useState(false);


  const changePasswordState = () => {
    setShowPassword(!showPassword);
  };
    // Password toggle handler
    const togglePassword = () => {

        setPasswordShown(!passwordShown);
      };
    
      const togglePassword2 = () => {

        setPasswordShown1(!passwordShown1);
      };
    



  return (
    <div>
         <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      {/* <Main> */}
      <form>
                      {/* <input type={passwordShown ? "text" : "password"} autoComplete="off" value={value} onChange={(event)=>{ console.log(event.target.value) ; setValue(event.target.value)}}  placeholder={passwordShown ? "text" : "password"}/>
                      <div onClick={togglePassword}>Show Password</div> */}
                      </form>
                      <Header />
          <div className='col-md-12 text-center padding_top_equal_booking_page'>
            <img className='img-fluid' src='../images/expertlog.png' />
            <div className='col-md-12 px-5 pt-4'>
                <div className='row'>
                    <div className='col-md-4'></div>
                    <div className='col-md-4 '>
                        <div className='col-md-12 text-start'>
                        
                        <div className='col-md-12'>
                        <p className='mb-2 text_mobile_booking'>Enter your password</p>
                        <div className='display_flex_input'>
                        <input className='form-control form_input_style' type={passwordShown1 ? "text" : "password"} value={value1} onChange={(event)=>{ console.log(event.target.value) ; setValue1(event.target.value)}} /><span><button className='btn btn-light btn_style_input pb-2 '> <span onClick={togglePassword2}> <AiOutlineEye /></span></button></span>
                      </div>
                     
                      <p className='mb-2 mt-2 text_mobile_booking'>Please confirm your password</p>
                      <div className='display_flex_input'>
                        <input className='form-control form_input_style' type={passwordShown ? "text" : "password"} value={value} onChange={(event)=>{ console.log(event.target.value) ; setValue(event.target.value)}} /><span><button className='btn btn-light btn_style_input pb-2 '> <span onClick={togglePassword}> <AiOutlineEye /></span></button></span>
                      </div>
                        </div>
                       
                        <Link href="/industries-booking/industries-profile" > <button className='btn btn-danger px-4 pb-2 mt-3 background_booking_button'>
                            Next
                        </button></Link>
                        </div>
                    </div>
                    <div className='col-md-4'></div>
                </div>
            </div>
          </div>
        
        {/* </Main> */}
        </div>
  )
}

export default Industriespassword