import Head from 'next/head';
import Link from 'next/link';
import React from 'react'
import Header from '../Industries/Header/Header'
import { AiOutlineEye, AiOutlineEyeInvisible,AiOutlineUser,AiOutlineMail } from "react-icons/ai";
// import {AiOutlineUser} from "react-icons/bi"
import Form from 'react-bootstrap/Form';

function industriesprofile() {
  return (
<div>
         <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
    
          <Header />
          <div className='col-md-12 text-center padding_top_equal_booking_page1'>
            <img className='img-fluid' src='../images/expertlog.png' />
            <div className='col-md-12 px-5 pt-4'>
                <div className='row'>
                    <div className='col-md-4'></div>
                    <div className='col-md-4 '>
                        <div className='col-md-12 text-start mb-4'>
                            <form>
                        
                        <div className='col-md-12'>
                        <p className='mb-2 text_mobile_booking'>Enter First Name</p>
                        <div className='display_flex_input'>
                        <span><button className='btn btn-light form_btn_style2 pb-2 '> <span className='icon_red' > <AiOutlineUser /></span></button></span><input required className='form-control form_input_style1' />
                      </div>

                      <p className='mb-2 text_mobile_booking mt-2'>Enter your Last Name</p>
                        <div className='display_flex_input'>
                        <span><button className='btn btn-light form_btn_style2 pb-2 '> <span className='icon_red' > <AiOutlineUser /></span></button></span><input required className='form-control form_input_style1' />
                      </div>
                      <p className='mb-2 text_mobile_booking mt-2'>Add your email information</p>
                        <div className='display_flex_input'>
                        <span><button className='btn btn-light form_btn_style2 pb-2 '> <span className='icon_red' > <AiOutlineMail /></span></button></span><input required className='form-control form_input_style1' />
                      </div>

                      <p className='mb-2 text_mobile_booking mt-2'>Add Gender</p>
                        <div className=''>
                       
                            <div className="display_flex_radio">
                           <span> <Form.Check 
                                type="radio"
                                id="radio"
                                label="Male"
                                name="radio"
                            /></span>&nbsp;&nbsp;
                            <span> <Form.Check 
                                type="radio"
                                id="radio"
                                label="Female"
                                name="radio"
                            /></span>&nbsp;&nbsp;
                             <span> <Form.Check 
                                type="radio"
                                id="radio"
                                label="Other"
                                name="radio"
                            /></span>
                            </div>
                      </div>
                        </div>
                       
                        <Link href="/industries-booking/industries-email-otp" > <button type='submit' className='btn btn-danger px-4 pb-2 mt-3 background_booking_button'>
                            Confirm
                        </button></Link>
                        </form>
                        </div>
                    </div>
                    <div className='col-md-4'></div>
                </div>
            </div>
          </div>
        </div>
  )
}

export default industriesprofile