import { Main } from 'next/document'
import Head from 'next/head'
import React from 'react'
import Header from '../Industries/Header/Header'
import styled from "styled-components"
import JsonData from "../Industries/Catagoriesdata/Catagoriesdata.json";
import Link from 'next/link'

function Industrieslisting() {
  const Main=styled.main``
  return (
    <>
        <Head>
        {/* <title>Expert || Any Service | Any Time | Any Where</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" /> */}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
          crossOrigin="anonymous"
        />
      </Head>
      <Main>
      <Header />
      <div className='col-md-12 pt-3 padding_left_right_listing'>
        <div className='col-md-12 text-center'>
          <h5><b>Mens Tailoring</b></h5>
        </div>
        {
            JsonData.ListingInd.map((item, index)=>{
              return(
                <Link className='simple_decoration_link' href={`/industries-booking/${item.id}`}>  <div className='col-md-12 mt-3 background_card_white p-2'>
         
                <div className='row '>
                <div className='col-md-3 '>
                  <img className='img-fluid width_img_loading' src='../images/loadingimage.jpg' />
                </div>
                <div className='col-md-6 m-auto'><p> {item.title}</p></div>
                <div className='col-md-3 m-auto'>
                  <h6><b>{item.price}</b></h6>
                </div>
              </div>
              
           
        </div>
        </Link>
             ) })
         
        }
      </div>
      </Main>
      </>
  )
}

export default Industrieslisting